version: '3'
services:

  zookeeper:
    image: mesoscloud/zookeeper:3.4.6-ubuntu-14.04
    hostname: "zookeeper"
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  mesos-master:
    image: datastrophic/mesos-master:1.1.0
    hostname: "mesos-master"
    container_name: master
    privileged: true
    environment:
      - MESOS_HOSTNAME=mesos-master
      - MESOS_CLUSTER=SMACK
      - MESOS_QUORUM=1
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - MESOS_LOG_DIR=/tmp/mesos/logs
    links:
      - zookeeper
    ports:
      - "5050:5050"

  mesos-slave-1:
    image: datastrophic/mesos-slave:1.1.0
    hostname: "mesos-slave-1"
    container_name: slave-1
    privileged: true
    environment:
      - MESOS_HOSTNAME=mesos-slave-1
      - MESOS_PORT=5151
      - MESOS_MASTER=zk://zookeeper:2181/mesos
    links:
      - zookeeper
      - mesos-master
    ports:
      - "5151:5151"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mesos-slave-2:
    image: datastrophic/mesos-slave:1.1.0
    hostname: "mesos-slave-2"
    container_name: slave-2
    privileged: true
    environment:
      - MESOS_HOSTNAME=mesos-slave-2
      - MESOS_PORT=5152
      - MESOS_MASTER=zk://zookeeper:2181/mesos
    links:
      - zookeeper
      - mesos-master
    ports:
      - "5152:5152"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock